variable "enabled" {
  description = "Set to false to prevent the module from creating anything"
  default     = true
}

variable "acknowledgement_timeout" {
  description = "Pagerduty service acknowledgement timeout"
  default     = "null"
}

variable "auto_resolve_timeout" {
  description = "Pagerduty service auto resolve timeout"
  default     = "null"
}

variable "policy_description" {
  description = "Escalation policy description"
  default     = "Managed by Terraform"
}

variable "policy_loops" {
  description = "Number of times to repeat the escalation policy"
  default     = 2
}

variable "policy_name" {
  description = "Escalation policy name"
}

variable "service_description" {
  description = "Pagerduty service description"
  default     = "Managed by Terraform"
}

variable "service_name" {
  description = "Pagerduty service name"
}

variable "slack_extension_name" {
  description = "Pagerduty service Slack extension name"
  default     = ""
}

variable "escalation_rules" {
  description = "Data structure generated by script from json file"
  type        = "list"
  default     = []
}

variable "teams" {
  description = "Data structure generated by script from json file"
  type        = "list"
  default     = []
}
